services:
  reductstore:
    image: reduct/store:latest
    container_name: reductstore
    environment:
      RS_DATA_PATH: /data

      RS_BUCKET_1_NAME: data
      RS_BUCKET_1_QUOTA_TYPE: FIFO
      RS_BUCKET_1_QUOTA_SIZE: 1GB

      RS_REPLICATION_1_NAME: repl-task
      RS_REPLICATION_1_SRC_BUCKET: data
      RS_REPLICATION_1_DST_HOST: https://play.reduct.store
      RS_REPLICATION_1_DST_TOKEN: reductstore
      RS_REPLICATION_1_DST_BUCKET: demo
      RS_REPLICATION_1_WHEN: '{"&score": {"$$gt": 0.8}}'

    volumes:
      - ./data:/data
    ports:
      - 8383:8383